generator: admingenerator.generator.doctrine
params:
    model: Manticora\PushNotificationBundle\Entity\Client
    namespace_prefix: Manticora
    concurrency_lock: ~
    bundle_name: PushNotificationBundle
    pk_requirement: ~
    fields: ~
    object_actions:
        delete: ~
    batch_actions:
        delete: ~
builders:
    list:
        params:
            title: List for PushNotificationBundle
            display: ~
            actions:
                new: ~
            object_actions:
                edit: ~
                delete: ~
    filters:
        params:
            display: ~
    new:
        params:
            title: New object for PushNotificationBundle
            display: [type, token, description]
            actions:
                save: ~
                list: ~
    edit:
        params:
            title: "You're editing the object \"%object%\"|{ %object%: Client.description }|"
            display: [type, token, description]
            actions:
                save: ~
                list: ~
    show:
        params:
            title: "You're viewing the object \"%object%\"|{ %object%: Client.description }|"
            display: [type, token, description]
            actions:
                list: ~
                new: ~
    actions:
        params:
            object_actions:
                delete: ~
            batch_actions:
                delete: ~
