generator: admingenerator.generator.doctrine
params:
    model: Manticora\PushNotificationBundle\Entity\MessageTemplate
    namespace_prefix: Manticora
    concurrency_lock: ~
    bundle_name: PushNotificationBundle
    pk_requirement: ~
    fields:
           attributes:
             dbType: collection
             formType: afe_collection_table
             addFormOptions:
                 allow_add:      true
                 allow_delete:   true
                 type: \Manticora\PushNotificationBundle\Form\MessageAttributeType
                 by_reference: false
                 options:
                    label:          Add new item
                    data_class:     Manticora\PushNotificationBundle\Entity\MessageAttribute
    object_actions:
        delete: ~
    batch_actions:
        delete: ~
builders:
    list:
        params:
            title: List for PushNotificationBundle
            display: ~
            actions:
                new: ~
            object_actions:
                edit: ~
                delete: ~
    filters:
        params:
            display: ~
    new:
        params:
            title: New object for PushNotificationBundle
            display: [name, description, attributes]
            actions:
                save: ~
                list: ~
    edit:
        params:
            title: "You're editing the object \"%object%\"|{ %object%: MessageTemplate.description }|"
            display: [name, description, attributes]
            actions:
                save: ~
                list: ~
    show:
        params:
            title: "You're viewing the object \"%object%\"|{ %object%: MessageTemplate.description }|"
            display: [name, description, attributes]
            actions:
                list: ~
                new: ~
    actions:
        params:
            object_actions:
                delete: ~
            batch_actions:
                delete: ~
