generator: admingenerator.generator.doctrine
params:
    model: Manticora\PushNotificationBundle\Entity\Message
    namespace_prefix: Manticora
    concurrency_lock: ~
    bundle_name: PushNotificationBundle
    pk_requirement: ~
    fields:
           attributes:
             dbType: collection
             formType: afe_collection_table
             addFormOptions:
                 allow_add:      true
                 allow_delete:   true
                 type: \Manticora\PushNotificationBundle\Form\MessageAttributeType
                 by_reference: false
                 options:
                    label:          Add new item
                    data_class:     Manticora\PushNotificationBundle\Entity\MessageAttribute
    object_actions:
        delete: ~
    batch_actions:
        delete: ~
builders:
    list:
        params:
            title: List for PushNotificationBundle
            display: [enable, progress,  type, description, active]
            actions:
                new: ~
            object_actions:
                send:
                  route: push_send
                edit: ~
                delete: ~
    filters:
        params:
            display: ~
    new:
        params:
            title: New object for PushNotificationBundle
            display: [description, type, cronstring, enable, push_all, active, start_time, stop_time, attributes]
            actions:
                save: ~
                list: ~
    edit:
        params:
            title: "You're editing the object |{ %object%: Message.description  }|"
            display: [description, type, cronstring, enable, push_all, active, start_time, stop_time, attributes]
            actions:
                save: ~
                list: ~
    show:
        params:
            title: "You're viewing the object |{ %object%: Message.description  }|"
            display: [description, type, template, cronstring, enable, push_all, active, start_time, stop_time]
            actions:
                list: ~
                new: ~
    actions:
        params:
            object_actions:
                delete: ~
            batch_actions:
                delete: ~
