<?php

namespace Manticora\PushNotificationBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * MessageAttributeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MessageAttributeRepository extends EntityRepository
{
}