ManticoraPushNotificationBundle_admin_manticora_push_notification_bundle_MessageTemplate:
    resource: "@ManticoraPushNotificationBundle/Controller/MessageTemplate/"
    type:     admingenerator
    prefix:   /manticora_push_notification_bundle/MessageTemplate

ManticoraPushNotificationBundle_admin_mash_frog_push_notification_bundle_MessageGroup:
    resource: "@ManticoraPushNotificationBundle/Controller/MessageGroup/"
    type:     admingenerator
    prefix:   /message_group

ManticoraPushNotificationBundle_admin_mash_frog_push_notification_bundle_MessageAttribute:
    resource: "@ManticoraPushNotificationBundle/Controller/MessageAttribute/"
    type:     admingenerator
    prefix:   /message_attribute

ManticoraPushNotificationBundle_admin_mash_frog_push_notification_bundle_MessageType:
    resource: "@ManticoraPushNotificationBundle/Controller/MessageType/"
    type:     admingenerator
    prefix:   /message_type

ManticoraPushNotificationBundle_admin_mash_frog_push_notification_bundle_Client:
    resource: "@ManticoraPushNotificationBundle/Controller/Client/"
    type:     admingenerator
    prefix:   /client

ManticoraPushNotificationBundle_admin_mash_frog_push_notification_bundle_message:
    resource: "@ManticoraPushNotificationBundle/Controller/Message/"
    type:     admingenerator
    prefix:   /message


